name: Test Workflow  # Ime delovnega toka

on:
  push:
    branches:
      - master # test se zažene po potisku na glavno vejo

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Uporabi akcijo za preverjanje kode

      - name: Set up Python
        uses: actions/setup-python@v2  # Uporabi akcijo za nastavitev Pythona
        with:
          python-version: '3.9'  # Različica Pythona 3.9

      - name: Install dependencies  # Namesti odvisnosti s pip
        run: |
          pip install numpy pytest opencv-python

      - name: Save environment setup artifacts  # Shrani rezultat namestitve v datoteko setup_status.txt
        run: |
          echo "Okolje uspešno nameščeno!" > setup_status.txt
        continue-on-error: true  # Nadaljuj tudi ob napaki

      - name: Upload setup artifacts  # Naloži rezultate namestitve kot artefakte
        uses: actions/upload-artifact@v2
        with:
          name: setup-artifacts  # Ime artefakta
          path: setup_status.txt  # Pot do datoteke

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - name: Download setup artifacts  # Prenesi artefakte iz prejšnjega dela
        uses: actions/download-artifact@v2
        with:
          name: setup-artifacts

      - name: Check environment setup status  # Preveri status namestitve okolja
        run: |
          if [ -f setup_status.txt ]; then  # Če obstaja datoteka setup_status.txt
            cat setup_status.txt  # Izpiši vsebino datoteke
          else
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve."
            echo "Napaka: Namestitev okolja ni uspela. Preverite dnevnike namestitve." > error.txt
          fi
        continue-on-error: true  # Nadaljuj tudi ob napaki

      - name: Run tests  # Zaženi teste
        run: |
          pytest test.py
        continue-on-error: true  # Nadaljuj tudi ob napaki

      - name: Check for test errors  # Preveri, ali so se pri testiranju pojavile napake
        run: |
          if [ -f error.txt ]; then  # Če obstaja datoteka error.txt
            echo "Napaka: Testi so spodleteli. Glejte dnevnike testiranja za podrobnosti."
            echo "Napaka: Testi so spodleteli. Glejte dnevnike testiranja za podrobnosti." > test_error.txt
            exit 1
          fi
